name: Continuous integration - private registry

on:
  pull_request:
  merge_group:

jobs:
  test-net-private:
    name: Test Suite (network-enabled tests)
    runs-on: ubuntu-latest
    environment: main
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - "1.81.0"  # MSRV
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      # - name: Run cargo test (test-net-private)
      #   run: cargo test --features test-net,test-net-private
      #   env:
      #     DOCKER_REGISTRY_QUAY_USER: ${{ secrets.DOCKER_REGISTRY_QUAY_USER }}
      #     DOCKER_REGISTRY_QUAY_PASSWD: ${{ secrets.DOCKER_REGISTRY_QUAY_PASSWD }}
